plugins {
    id 'java'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '5.3.9'
}


repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    testImplementation 'net.serenity-bdd:serenity-core:5.3.9'
    testImplementation 'net.serenity-bdd:serenity-cucumber:5.3.9'
    testImplementation 'net.serenity-bdd:serenity-junit5:5.3.9'

    testImplementation 'io.cucumber:cucumber-java:7.20.1'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.20.1'

    testImplementation 'org.junit.platform:junit-platform-suite:1.12.2'

    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.16'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
    finalizedBy 'aggregate'
}